import paintBucket1 from "@/assets/paint-bkt-1.png";
import paintBucket2 from "@/assets/paint-bkt-2.png";
import paintBucket3 from "@/assets/paint-bkt-3.png";
import paintBrush   from "@/assets/paint-brush-1.png";
import roller       from "@/assets/roller.png";
import spray        from "@/assets/spray.png";

export const defaultProducts = [
  {
    id: 1,
    name: "DRIP Royal Velvet Touch — Silk Emulsion",
    category: "Interior Paint",
    price: 3450,
    unit: "/ gallon",
    stock: 45,
    rating: "★★★★★",
    ratingScore: 5.0,
    reviews: 184,
    image: paintBucket1,
    description: "Ultra-luxury architectural interior emulsion formulated with stain-resistant nanotech, anti-bacterial protection, and washable rich velvet pigments. Ideal for master bedrooms, drawing rooms, and luxury living spaces.",
    sheen: "Soft Velvet Silk",
    coverage: "400 – 450 sq. ft. per gallon",
    dryTime: "30 min touch, 2 hours recoat",
    cleanup: "Warm soapy water",
    isPaint: true,
    featured: true,
  },
  {
    id: 2,
    name: "DRIP Cashmere Ultra-Matte — Wall Coating",
    category: "Interior Paint",
    price: 2950,
    unit: "/ gallon",
    stock: 38,
    rating: "★★★★★",
    ratingScore: 4.9,
    reviews: 142,
    image: paintBucket3,
    description: "Flawless non-reflective chalk matte finish that conceals wall imperfections and surface flaws. Zero VOC eco-formulation ensuring clean, odorless indoor air quality.",
    sheen: "Ultra-Matte Chalk",
    coverage: "380 – 420 sq. ft. per gallon",
    dryTime: "30 min touch, 2 hours recoat",
    cleanup: "Soap & warm water",
    isPaint: true,
    featured: true,
  },
  {
    id: 3,
    name: "DRIP All-Weather Monsoon Shield — Pure Acrylic",
    category: "Exterior Paint",
    price: 3850,
    unit: "/ gallon",
    stock: 52,
    rating: "★★★★★",
    ratingScore: 4.9,
    reviews: 215,
    image: paintBucket2,
    description: "Heavy-duty 10-year monsoon weather shield engineered with cross-linking 100% pure acrylic polymers. Resists intense UV radiation, heavy rain, dampness, and fungus.",
    sheen: "Low-Lustre Weather Satin",
    coverage: "320 – 380 sq. ft. per gallon",
    dryTime: "1 hour touch, 4 hours recoat",
    cleanup: "Water & detergent",
    isPaint: true,
    featured: true,
  },
  {
    id: 4,
    name: "DRIP SolarReflect Thermal Cool Roof & Wall Coat",
    category: "Exterior Paint",
    price: 4200,
    unit: "/ gallon",
    stock: 26,
    rating: "★★★★★",
    ratingScore: 4.8,
    reviews: 98,
    image: paintBucket2,
    description: "Advanced high-solar-reflectance index (SRI) coating that reflects up to 90% of solar heat, reducing indoor ambient temperatures by up to 5°C and saving energy.",
    sheen: "Reflective Matte",
    coverage: "280 – 320 sq. ft. per gallon",
    dryTime: "2 hours touch, 6 hours recoat",
    cleanup: "Water",
    isPaint: true,
    featured: true,
  },
  {
    id: 5,
    name: "DRIP Hydro-Shield Damp-Proof Wall Sealer",
    category: "Primers & Sealers",
    price: 2250,
    unit: "/ gallon",
    stock: 60,
    rating: "★★★★★",
    ratingScore: 4.9,
    reviews: 167,
    image: paintBucket1,
    description: "Deep penetrating waterproofing primer and efflorescence barrier. Locks moisture out of plaster and concrete masonry to prevent bubbling and flaking.",
    sheen: "Penetrating Sealer",
    coverage: "350 – 400 sq. ft. per gallon",
    dryTime: "45 min touch, 3 hours recoat",
    cleanup: "Warm water",
    isPaint: true,
    featured: true,
  },
  {
    id: 6,
    name: "DRIP Ultra-Grip Universal Multi-Surface Primer",
    category: "Primers & Sealers",
    price: 1950,
    unit: "/ gallon",
    stock: 40,
    rating: "★★★★☆",
    ratingScore: 4.7,
    reviews: 83,
    image: paintBucket3,
    description: "High-bonding acrylic undercoat designed for fresh drywall, plaster, wood, and previously painted glossy surfaces for maximum topcoat adhesion.",
    sheen: "Adhesion Primer",
    coverage: "350 – 400 sq. ft. per gallon",
    dryTime: "30 min touch, 2 hours recoat",
    cleanup: "Water & soap",
    isPaint: true,
    featured: false,
  },
  {
    id: 7,
    name: "DRIP Mirror-Gloss Polyurethane Enamel — Doors & Metal",
    category: "Interior Paint",
    price: 2650,
    unit: "/ gallon",
    stock: 30,
    rating: "★★★★★",
    ratingScore: 4.9,
    reviews: 110,
    image: paintBucket1,
    description: "Ultra-tough synthetic polyurethane enamel delivering a brilliant mirror gloss on wooden doors, window trim, metal gates, and railings.",
    sheen: "Mirror High-Gloss",
    coverage: "400 – 460 sq. ft. per gallon",
    dryTime: "2 hours touch, 8 hours recoat",
    cleanup: "Mineral spirits",
    isPaint: true,
    featured: true,
  },
  {
    id: 8,
    name: "DRIP Satinwood Timber Shield — Polyurethane Varnish",
    category: "Interior Paint",
    price: 2800,
    unit: "/ gallon",
    stock: 22,
    rating: "★★★★☆",
    ratingScore: 4.8,
    reviews: 76,
    image: paintBucket2,
    description: "Premium UV-blocking wood stain and protective varnish that highlights natural teak, walnut, and oak grains while guarding against moisture and scratches.",
    sheen: "Silky Satin",
    coverage: "380 – 420 sq. ft. per gallon",
    dryTime: "1.5 hours touch, 6 hours recoat",
    cleanup: "Mineral spirits",
    isPaint: true,
    featured: false,
  },
  {
    id: 9,
    name: "MasterCraft 5-Piece Precision Synthetic Brush Set",
    category: "Brushes",
    price: 1450,
    unit: "/ set",
    stock: 35,
    rating: "★★★★★",
    ratingScore: 4.9,
    reviews: 95,
    image: paintBrush,
    description: "Handcrafted flagged synthetic bristles engineered for razor-sharp cutting-in lines, trim work, and zero filament shedding. Includes 1\", 1.5\", 2\", 2.5\", and 3\" angle brushes.",
    sheen: "N/A",
    coverage: "N/A",
    dryTime: "N/A",
    cleanup: "Rinse immediately after use",
    isPaint: false,
    featured: true,
  },
  {
    id: 10,
    name: "ProGlide 9\" Microfiber Roller & Heavy-Duty Frame",
    category: "Rollers & Frames",
    price: 1250,
    unit: "/ set",
    stock: 48,
    rating: "★★★★★",
    ratingScore: 4.9,
    reviews: 130,
    image: roller,
    description: "Ultra-dense non-shedding microfiber 3/8\" nap roller with a 5-wire heavy-duty chrome cage frame. Distributes paint evenly with zero splatter for glass-smooth wall finish.",
    sheen: "N/A",
    coverage: "N/A",
    dryTime: "N/A",
    cleanup: "Wash with warm water and spin dry",
    isPaint: false,
    featured: true,
  },
  {
    id: 11,
    name: "AeroFlow Pro 850W Electric HVLP Spray Station",
    category: "Spray Equipment",
    price: 8900,
    unit: "/ unit",
    stock: 14,
    rating: "★★★★★",
    ratingScore: 5.0,
    reviews: 64,
    image: spray,
    description: "Professional 850-Watt high-volume low-pressure turbine spray gun with 3 adjustable brass nozzles (round, horizontal, vertical). Delivers factory-level spray finishes in 1/3 the time.",
    sheen: "N/A",
    coverage: "N/A",
    dryTime: "N/A",
    cleanup: "Flush with solvent/water immediately",
    isPaint: false,
    featured: true,
  },
  {
    id: 12,
    name: "CleanLine Razor-Edge Multi-Surface Painter's Tape (3-Pack)",
    category: "Brushes",
    price: 850,
    unit: "/ pack",
    stock: 65,
    rating: "★★★★☆",
    ratingScore: 4.8,
    reviews: 52,
    image: paintBrush,
    description: "Treated with PaintBlock technology to react with latex paint and instantly form a micro-barrier for ultra-sharp paint lines. 14-day clean removal with zero residue.",
    sheen: "N/A",
    coverage: "N/A",
    dryTime: "N/A",
    cleanup: "Disposable",
    isPaint: false,
    featured: false,
  },
];

export function getFallbackProducts() {
  return defaultProducts;
}
